onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/clk
add wave -noupdate /testbench/reset
add wave -noupdate /testbench/dut/clk
add wave -noupdate /testbench/dut/reset
add wave -noupdate /testbench/dut/instr
add wave -noupdate -radix hexadecimal /testbench/dut/imm
add wave -noupdate /testbench/dut/alu_result
add wave -noupdate /testbench/dut/reg_rdata1
add wave -noupdate /testbench/dut/reg_rdata2
add wave -noupdate /testbench/dut/dmem_rdata
add wave -noupdate /testbench/dut/reg_wdata
add wave -noupdate /testbench/dut/alu_op2
add wave -noupdate /testbench/dut/next_pc
add wave -noupdate /testbench/dut/alu_ctrl
add wave -noupdate /testbench/dut/branch_taken
add wave -noupdate /testbench/dut/reg_we
add wave -noupdate /testbench/dut/dmem_we
add wave -noupdate /testbench/dut/pc
add wave -noupdate /testbench/dut/imem/addr
add wave -noupdate /testbench/dut/imem/instr
add wave -noupdate /testbench/dut/ig/instr
add wave -noupdate /testbench/dut/ig/imm
add wave -noupdate /testbench/dut/rf/clk
add wave -noupdate /testbench/dut/rf/we
add wave -noupdate /testbench/dut/rf/raddr1
add wave -noupdate /testbench/dut/rf/raddr2
add wave -noupdate /testbench/dut/rf/waddr
add wave -noupdate /testbench/dut/rf/wdata
add wave -noupdate /testbench/dut/rf/rdata1
add wave -noupdate /testbench/dut/rf/rdata2
add wave -noupdate /testbench/dut/alu_ctrl_unit/opcode
add wave -noupdate /testbench/dut/alu_ctrl_unit/funct3
add wave -noupdate /testbench/dut/alu_ctrl_unit/funct7
add wave -noupdate /testbench/dut/alu_ctrl_unit/alu_ctrl
add wave -noupdate /testbench/dut/alu_unit/op1
add wave -noupdate /testbench/dut/alu_unit/op2
add wave -noupdate /testbench/dut/alu_unit/alu_ctrl
add wave -noupdate /testbench/dut/alu_unit/result
add wave -noupdate /testbench/dut/branch_unit/op1
add wave -noupdate /testbench/dut/branch_unit/op2
add wave -noupdate /testbench/dut/branch_unit/branch_en
add wave -noupdate /testbench/dut/branch_unit/branch_taken
add wave -noupdate /testbench/dut/dmem/clk
add wave -noupdate /testbench/dut/dmem/we
add wave -noupdate /testbench/dut/dmem/addr
add wave -noupdate /testbench/dut/dmem/wdata
add wave -noupdate /testbench/dut/dmem/rdata
add wave -noupdate /testbench/dut/core/clk
add wave -noupdate /testbench/dut/core/reset
add wave -noupdate /testbench/dut/core/instr
add wave -noupdate /testbench/dut/core/reg_rdata1
add wave -noupdate /testbench/dut/core/reg_rdata2
add wave -noupdate /testbench/dut/core/dmem_rdata
add wave -noupdate /testbench/dut/core/imm
add wave -noupdate /testbench/dut/core/alu_ctrl
add wave -noupdate /testbench/dut/core/branch_taken
add wave -noupdate /testbench/dut/core/pc
add wave -noupdate /testbench/dut/core/next_pc
add wave -noupdate /testbench/dut/core/alu_result
add wave -noupdate /testbench/dut/core/reg_we
add wave -noupdate /testbench/dut/core/dmem_we
add wave -noupdate /testbench/dut/core/reg_wdata
add wave -noupdate /testbench/dut/core/alu_op2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4907983 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {4894584 ps} {4982172 ps}
